version: "3.9"

services:
  faster-whisper:
    image: fedirz/faster-whisper-server:latest-cpu
    container_name: faster_whisper_cpu
    ports:
      - "8001:8000"
    volumes:
      - ./cache/huggingface:/root/.cache/huggingface